version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: complianceiq
      POSTGRES_USER: complianceiq
      POSTGRES_PASSWORD: complianceiq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U complianceiq -d complianceiq"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: complianceiq-backend:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://complianceiq:complianceiq@postgres:5432/complianceiq
      SERVICE_ACCOUNT_TOKEN: ${SERVICE_ACCOUNT_TOKEN:-local-dev-token}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@complianceiq.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-ChangeMe123!}
      ENVIRONMENT: docker
    ports:
      - "8100:8000"

volumes:
  postgres_data:
